// Generated by CoffeeScript 1.6.1
(function() {

  window.game = window.game || {};

  game.GameOver = cc.LayerColor.extend({
    _won: false,
    ctor: function() {
      this._super();
      return cc.associateWithNative(this, cc.LayerColor);
    },
    onEnter: function() {
      var centerPos, director, label, message, winSize;
      this._super();
      director = cc.Director.getInstance();
      winSize = director.getWinSize();
      centerPos = cc.p(winSize.width / 2, winSize.height / 2);
      message = void 0;
      if (this._won) {
        message = "You Won!";
      } else {
        message = "You Lose :[";
      }
      label = cc.LabelTTF.create(message, "Arial", 32);
      label.setColor(cc.c3b(0, 0, 0));
      label.setPosition(winSize.width / 2, winSize.height / 2);
      this.addChild(label);
      return this.runAction(cc.Sequence.create(cc.DelayTime.create(3), cc.CallFunc.create(function(node) {
        var scene;
        scene = new game.IntroScreenScene();
        return cc.Director.getInstance().replaceScene(scene);
      }, this)));
    }
  });

  game.GameOver.create = function(won) {
    var sg;
    sg = new game.GameOver();
    sg._won = won;
    if (sg && sg.init(cc.c4b(255, 255, 255, 255))) {
      return sg;
    }
    return null;
  };

  game.GameOver.scene = function(won) {
    var layer, scene;
    if (won == null) {
      won = true;
    }
    scene = cc.Scene.create();
    layer = game.GameOver.create(won);
    scene.addChild(layer);
    return scene;
  };

}).call(this);
