// Generated by CoffeeScript 1.6.1
(function() {

  window.game = window.game || {};

  /*
  Copyright (c) 2010-2012 cocos2d-x.org
  Copyright (c) 2008-2010 Ricardo Quesada
  Copyright (c) 2011      Zynga Inc.
  
  http://www.cocos2d-x.org
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
  */


  game.CircleSprite = cc.Sprite.extend({
    _radians: 0,
    ctor: function() {
      return this._super();
    },
    draw: function() {
      cc.renderContext.fillStyle = "rgba(255,255,255,1)";
      cc.renderContext.strokeStyle = "rgba(255,255,255,1)";
      if (this._radians < 0) {
        this._radians = 360;
      }
      return cc.drawingUtil.drawCircle(cc.PointZero(), 30, cc.DEGREES_TO_RADIANS(this._radians), 60, true);
    },
    myUpdate: function(dt) {
      return this._radians -= 6;
    }
  });

  game.Helloworld = cc.Layer.extend({
    isMouseDown: false,
    helloImg: null,
    helloLabel: null,
    circle: null,
    sprite: null,
    addDelayToObject: function(object) {
      return this.scheduleOnce(function() {
        return object.setVisible(true);
      }, 1.0);
    },
    addTitleSprite: function(size) {
      this.titleSprite = cc.Sprite.create("res/Title/TitleText.png");
      this.titleSprite.setPosition(cc.p(size.width / 2, 0));
      this.titleSprite.setScale(0.5);
      this.addChild(this.titleSprite, 10);
      return this.titleSprite.runAction(cc.MoveBy.create(0.8, cc.p(0, size.height - 210)));
    },
    addAsShipSprite: function(size, lazyLayer) {
      if (lazyLayer == null) {
        lazyLayer = this;
      }
      this.asShipSprite = cc.MenuItemImage.create("res/Title/AsShip.png", "res/Title/AsShip.png", function() {
        return console.log("new game");
      }, this);
      this.asShipSprite.setPosition(cc.p(size.width / 4, size.height - 440));
      this.asShipSprite.setScale(0.5);
      this.asShipSprite.setVisible(false);
      lazyLayer.addChild(this.asShipSprite);
      return this.asShipSprite;
    },
    addAsDirectorSprite: function(size, lazyLayer) {
      if (lazyLayer == null) {
        lazyLayer = this;
      }
      this.asDirectorSprite = cc.MenuItemImage.create("res/Title/AsDirector.png", "res/Title/AsDirector.png", function() {
        return console.log("new game");
      }, this);
      this.asDirectorSprite.setPosition(cc.p((size.width / 4) * 3, size.height - 440));
      this.asDirectorSprite.setScale(0.5);
      this.asDirectorSprite.setVisible(false);
      lazyLayer.addChild(this.asDirectorSprite);
      return this.asDirectorSprite;
    },
    addMenuButton: function(size) {
      var closeItem, menu;
      closeItem = cc.MenuItemImage.create("res/CloseNormal.png", "res/CloseSelected.png", function() {
        return history.go(-1);
      }, this);
      closeItem.setAnchorPoint(cc.p(0.5, 0.5));
      menu = cc.Menu.create(closeItem);
      menu.setPosition(cc.PointZero());
      this.addChild(menu, 1);
      return closeItem.setPosition(cc.p(size.width - 20, 20));
    },
    init: function() {
      var backgroundLayer, directorSprite, lazyLayer, selfPointer, shipSprite, size;
      selfPointer = this;
      this._super();
      size = cc.Director.getInstance().getWinSize();
      backgroundLayer = new cc.LazyLayer();
      this.addChild(backgroundLayer);
      this.backgroundSprite = cc.Sprite.create("res/Splash.jpg");
      this.backgroundSprite.setPosition(cc.p(size.width / 2, size.height / 2));
      this.backgroundSprite.setScale(0.5);
      this.addChild(this.backgroundSprite);
      lazyLayer = new cc.LazyLayer();
      this.addChild(lazyLayer, 5);
      this.addMenuButton(size);
      this.addTitleSprite(size);
      shipSprite = this.addAsShipSprite(size);
      directorSprite = this.addAsDirectorSprite(size);
      this.addDelayToObject(shipSprite);
      this.addDelayToObject(directorSprite);
      this.setTouchEnabled(true);
      this.adjustSizeForWindow();
      lazyLayer.adjustSizeForCanvas();
      window.addEventListener("resize", function(event) {
        return selfPointer.adjustSizeForWindow();
      });
      return true;
    },
    adjustSizeForWindow: function() {
      var margin, parentDiv, xScale, yScale;
      margin = document.documentElement.clientWidth - document.body.clientWidth;
      if (document.documentElement.clientWidth < cc.originalCanvasSize.width) {
        cc.canvas.width = cc.originalCanvasSize.width;
      } else {
        cc.canvas.width = document.documentElement.clientWidth - margin;
      }
      if (document.documentElement.clientHeight < cc.originalCanvasSize.height) {
        cc.canvas.height = cc.originalCanvasSize.height;
      } else {
        cc.canvas.height = document.documentElement.clientHeight - margin;
      }
      xScale = cc.canvas.width / cc.originalCanvasSize.width;
      yScale = cc.canvas.height / cc.originalCanvasSize.height;
      if (xScale > yScale) {
        xScale = yScale;
      }
      cc.canvas.width = cc.originalCanvasSize.width * xScale;
      cc.canvas.height = cc.originalCanvasSize.height * xScale;
      parentDiv = document.getElementById("Cocos2dGameContainer");
      if (parentDiv) {
        parentDiv.style.width = cc.canvas.width + "px";
        parentDiv.style.height = cc.canvas.height + "px";
      }
      cc.renderContext.translate(0, cc.canvas.height);
      cc.renderContext.scale(xScale, xScale);
      return cc.Director.getInstance().setContentScaleFactor(xScale);
    },
    menuCloseCallback: function(sender) {
      return cc.Director.getInstance().end();
    },
    onTouchesBegan: function(touches, event) {
      return this.isMouseDown = true;
    },
    onTouchesMoved: function(touches, event) {
      if (this.isMouseDown) {
        return touches;
      }
    },
    onTouchesEnded: function(touches, event) {
      return this.isMouseDown = false;
    },
    onTouchesCancelled: function(touches, event) {
      return console.log("onTouchesCancelled");
    }
  });

  game.HelloWorldScene = cc.Scene.extend({
    onEnter: function() {
      var layer;
      this._super();
      layer = new game.Helloworld();
      layer.init();
      return this.addChild(layer);
    }
  });

}).call(this);
